name: Otomatik Playlist Guncelle

on:
  schedule:
    - cron: '0 */4 * * *' # Her 4 saatte bir otomatik çalışır
  workflow_dispatch: # İstediğinde elle başlatabilmen için

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Tarayici ve Kutuphaneleri Kur
        run: |
          pip install playwright requests
          python -m playwright install --with-deps chromium

      - name: Kanallari Guncelle
        run: python kanallar.py

      - name: Degisiklikleri Depoya Yukle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add kanallar.json playlist.m3u
          git commit -m "Otomatik guncelleme: JSON ve M3U yenilendi" || exit 0
          git push origin main
          
